<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        
        <title>修复 pycrypto AttributeError</title>
        
        <link rel="alternate" type="application/rss+xml" title="Xiaodong Xu" href="http://toy.linuxtoy.org/atom.xml">
        <link rel="shortcut icon" href="favicon.ico">
        <!-- syntax highlighting css -->
        <link rel="stylesheet" type="text/css" href="css/syntax.css">
        <!-- homepage css -->
        <link rel="stylesheet" type="text/css" href="css/hgtip/aal.css">
        <link rel="stylesheet" type="text/css" href="css/hgtip/calluna.css">
        <link rel="stylesheet" type="text/css" href="css/hgtip/style.css">
    </head>
    <body>
        <div id="main-wrap">
            <div id="header">
                <h1><a href="" title="Xiaodong Xu">Xiaodong Xu</a></h1>
            </div>
            <p id="navigation">
                <a href="pages/archives.html">archives</a> &mdash;
                <a href="pages/projects.html">projects</a> &mdash;
                <a href="pages/viml.html">viml</a> &mdash;
                <a href="pages/people.html">people</a> &mdash;
                <a href="pages/favorite.html">favorite</a> &mdash;
                <a href="pages/about.html">about</a>
            </p>
            <div id="content">
                
<h2>修复 pycrypto AttributeError</h2>

<p id="tip-info">December 20, 2013 @ 10:05 AM</p>
<p>在将 Ansible 升级到 1.4.2 时，其依赖模块 pycrpyto 也进行了<br />
更新，执行 <code class="highlighter-rouge">ansible</code> 报如下错误：</p>

<div class="highlighter-rouge"><pre class="highlight"><code>Traceback (most recent call last):
File "/usr/bin/ansible", line 24, in &lt;module&gt;
    from ansible.runner import Runner
File "/usr/lib/python2.6/site-packages/ansible/runner/__init__.py", line 53, in &lt;module&gt;
    from Crypto.Random import atfork
File "/usr/lib64/python2.6/site-packages/Crypto/Random/__init__.py", line 29, in &lt;module&gt;
    from Crypto.Random import _UserFriendlyRNG
File "/usr/lib64/python2.6/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 38, in &lt;module&gt;
    from Crypto.Random.Fortuna import FortunaAccumulator
File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaAccumulator.py", line 39, in &lt;module&gt;
    import FortunaGenerator
File "/usr/lib64/python2.6/site-packages/Crypto/Random/Fortuna/FortunaGenerator.py", line 34, in &lt;module&gt;
    from Crypto.Util.number import ceil_shift, exact_log2, exact_div
File "/usr/lib64/python2.6/site-packages/Crypto/Util/number.py", line 56, in &lt;module&gt;
    if _fastmath is not None and not _fastmath.HAVE_DECL_MPZ_POWM_SEC:
AttributeError: 'module' object has no attribute 'HAVE_DECL_MPZ_POWM_SEC'
</code></pre>
</div>

<p>打开 <code class="highlighter-rouge">/usr/lib64/python2.6/site-packages/Crypto/Util/number.py</code> 文件，可以<br />
看到 56 行上的注释说明，要求 libgmp 为 v5 以上版本。而系统现有版本为<br />
4.1.4，把 56 和 57 行暂时注释掉，Ansible 执行正常。</p>

<p>不过，此方法只是临时加以解决，更好的方式是去将 libgmp<br />
升级到符合要求的版本。</p>

<div id="tip-comments">
    <h2>Related Posts</h2>
    <ul>
        
        <li><a href="/2014/06/16/python-epub-doc.html">将 Python 文档打包成 ePub 格式</a> &raquo; June 16, 2014</li>
        
        <li><a href="/2014/06/13/switching-to-systemd-on-debian-jessie.html">Debian Jessie 切换 systemd</a> &raquo; June 13, 2014</li>
        
        <li><a href="/2014/05/09/pure-ftpd.html">使用 Pure-FTPd 架设 FTP 服务</a> &raquo; May  9, 2014</li>
        
    </ul>
</div>

            </div>
            <div id="footer">
                follow me: <a href="https://twitter.com/xuxiaodong">twitter</a> / <a href="https://plus.google.com/101096637428284023293/" rel="author">google+</a> / <a href="https://github.com/xuxiaodong">github</a> / <a href="http://www.linkedin.com/pub/xiaodong-xu/62/319/7">linkedin</a> / <a href="http://toy.linuxtoy.org/atom.xml">rss</a>
            </div>
        </div>
    </body>
</html>
